### ISSUE TITLE
Add examples of GitHub projects with efffective organization / structure

### ISSUE THREAD

**Issue by abbycabs** [mozilla/open-leadership-training-series#16]
Read article: https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/project-set-up-for-collaboration-with-github/#project-structure-and-organization

Add here: https://github.com/mozilla/open-leadership-training-series/blob/gh-pages/_articles/get-your-project-online/project-set-up-for-collaboration-with-github.md

**Comment by nufail** [comment]
Hi,

I'd like to work on this. Will send a PR soon

**Comment by abbycabs** [comment]
Thank you!

**Comment by betatim** [comment]
One project I like: https://github.com/nteract/nteract
