### ISSUE TITLE
mofo-bootstrap update

### ISSUE THREAD

**Issue by abbycabs** [mozilla/open-leadership-training-series#37]
Looks like [mofo bootstrap](https://github.com/mozilla/mofo-bootstrap/tree/gh-pages) updated -- so a few things look weird. We should consider locally serving mofo bootstrap

Things that I've noticed:
* [ ] font page title missing
* [ ] font generally smaller on article pages
![screen shot 2016-11-07 at 11 09 24](https://cloud.githubusercontent.com/assets/617994/20065032/ab29042e-a4da-11e6-9189-9328933c657e.png)

OR we can
* [ ] switch back to old bootstrap

**Comment by betatim** [comment]
Closed by #38
