### ISSUE TITLE
Remix the clubs certificate for OLTS project leads

### ISSUE THREAD

**Issue by abbycabs** [mozilla/open-leadership-training-series#47]
Clubs certificate:https://github.com/mozilla/learning.mozilla.org/issues/1849#issuecomment-222023623

This is in progress!

**Comment by abbycabs** [comment]
![olts-certificate-2](https://cloud.githubusercontent.com/assets/617994/20417183/a66aebd4-ad11-11e6-995f-1f71e379277b.jpg)

thoughts? flagging @flukeout, @betatim

**Comment by abbycabs** [comment]
Also flagging @chrislarry33 so he knows what else his name is on

**Comment by abbycabs** [comment]
Added certificate to redpen: https://redpen.io/uh0d30ab627475b2f4
Please leave feedback in there!

**Comment by flukeout** [comment]
@acabunoc If you want to pass me the illustrator file, I'm happy to make some tweaks etc.

**Comment by abbycabs** [comment]
Thanks @flukeout! Here's the file: https://drive.google.com/open?id=0B9UZnVcaoMU6clRJTFpoVU00S3c

**Comment by abbycabs** [comment]
I'm going to send these out later today, together with the exit survey! @flukeout

**Comment by flukeout** [comment]
Ok, I'll take a quick pass at it now and update the file with some minor changes. Should take about a half hour - that OK?

**Comment by flukeout** [comment]
Hey @acabunoc - I just made some very slight tweaks. For some reason the file was pretty hard to work with, what program did you modify it with?

https://dl.dropboxusercontent.com/u/109902/olts%20certificate.ai

![image](https://cloud.githubusercontent.com/assets/25212/20496667/f3a8af46-afda-11e6-8361-aca06eb9c98b.png)

**Comment by abbycabs** [comment]
Thanks @flukeout! Sorry about that -- I used an older version of illustrator and it didn't always play nice :(
