### ISSUE TITLE
Add Section on GitHub Projects

### ISSUE THREAD

**Issue by ghost** [mozilla/open-leadership-training-series#56]
It seems that GitHub now has a [tool for project management](https://github.com/blog/2272-introducing-projects-for-organizations).  Would it be worth it to add a section on the topic as it relates to leadership?

**Comment by betatim** [comment]
Thanks for the suggestion.I'm in two minds about this. On the one hand "ahrg, let's not make this yet another github tutorial" and on the other hand "let's show people how github makes it super easy for you to do things". So yeah :-/

Maybe we can add it to https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/#milestones ?

Personal comment: I prefer using milestones to plan/keep track of what is done/needs doing, but I know others who really like having a project board to organise what needs doing for the next release/milestone/event. Maybe someone who likes using projects can chime in and we could even link to their use as an example?

**Comment by ghost** [comment]
Not a problem and I agree with both of your sides (of the same coin). I will add some lines on that page in terms of using it as a roadmapping tool.  ~~But I think it should be also mentioned on the "[Open Project Maintenance](https://mozilla.github.io/open-leadership-training-series/articles/open-project-maintenance/open-project-maintenance/)" page, in the terms of task management.~~ I read the title of the page wrong after re-reading the page, it doesn't make sense on that page.

**Comment by ghost** [comment]
PR #58
